# Generated by Django 4.1.3 on 2022-12-30 06:10

import ExpState.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpState', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expstate',
            name='exp_id',
            field=models.JSONField(default=ExpState.models.jsonfield_default_value),
        ),
    ]
